name: Send Slack Message

on:
  schedule:
    - cron: '0 0 * * *'   # 매일 00:00 UTC (KST 09:00)
  workflow_dispatch:
    inputs:
      force_day:
        description: '강제로 보낼 날짜(5/10/15)'
        required: false

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install slack_sdk python-dotenv

      - name: Run
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          # 필요하면 채널도 시크릿/변수로 관리
          # SLACK_CHANNEL_ID: ${{ vars.SLACK_CHANNEL_ID }}
          FORCE_DAY: ${{ github.event.inputs.force_day }}
        run: python send_message.py
